services:
  - type: web
    name: phoenix
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: ""
    plan: starter
    healthCheckPath: /healthz
    envVars:
      - key: VITE_OBS_AGENT_URL
        value: "https://ai-obs-demo.onrender.com"
      - key: PHOENIX_SQL_DATABASE_URL
        fromDatabase:
          name: phoenix-db
          property: connectionString
      - key: PHOENIX_SECRET
        generateValue: true
      - key: PHOENIX_ENABLE_AUTH
        value: "true"

databases:
  - name: phoenix-db
    plan: starter
